### ISSUE TITLE
Getting Unexpected Exit Code 139 (specific versions, usually beta)

### ISSUE THREAD

**Issue by pablothedolphin** [webbertakken/unity-test-runner#54] opened 2020-04-03 13:23 UTC
This happens regardless of the editor version I use and regardless of either play mode or edit mode tests. It seems like the personal license is working so I'm struggling to see what's wrong:

Requesting activation (personal license)
Activation complete.
Using project path "/github/workspace/Test-Project".
Using artifacts path "editmode-artifacts" to save test results.
Using custom parameters .
Edit mode selected for testing.
Using Unity version "2020.1.0b4" to test.

###########################
#    Artifacts folder     #
###########################

Creating "/github/workspace/editmode-artifacts" if it does not exist.

###########################
#    Project directory    #
###########################

total 20K
drwxr-xr-x 5 1001 115 4.0K Apr  3 04:44 .
drwxr-xr-x 6 1001 115 4.0K Apr  3 04:46 ..
drwxr-xr-x 4 1001 115 4.0K Apr  3 04:44 Assets
drwxr-xr-x 2 1001 115 4.0K Apr  3 04:44 Packages
drwxr-xr-x 2 1001 115 4.0K Apr  3 04:44 ProjectSettings

###########################
#   Testing in EditMode   #
###########################

Segmentation fault (core dumped)
[Licensing::Module] Channel doesn't exist: "LicenseClient-root"
[Licensing::Module] Successfully launched the LicensingClient (PId: 70)
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-root"
[SignatureVerifier] Application signature verification not supported on this platform.
Entitlement-based licensing initiated
[LicensingClient] Licenses updated successfully
Unexpected exit code 139
/steps/run_tests.sh: line 109: [: =: unary operator expected

###########################
#    Project directory    #
###########################

total 20K
drwxr-xr-x 5 1001 115 4.0K Apr  3 04:44 .
drwxr-xr-x 6 1001 115 4.0K Apr  3 04:46 ..
drwxr-xr-x 4 1001 115 4.0K Apr  3 04:44 Assets
drwxr-xr-x 2 1001 115 4.0K Apr  3 04:44 Packages
drwxr-xr-x 2 1001 115 4.0K Apr  3 04:44 ProjectSettings

###########################
#    Edit Mode Results    #
###########################

cat: /github/workspace/editmode-artifacts/editmode-results.xml: No such file or directory
cat: /github/workspace/editmode-artifacts/editmode-results.xml: No such file or directory
/steps/run_tests.sh: line 164: [: =: unary operator expected
/steps/run_tests.sh: line 182: [: -gt: unary operator expected
##[error]The process '/usr/bin/docker' failed with exit code 139

**Comment by webbertakken** [comment] 2020-04-03 13:28
Hey @pablothedolphin adn thanks for reporting your issue!

Could you also show your workflow configuration for your test job?

**Comment by pablothedolphin** [comment] 2020-04-03 13:51
Here's my action script:

Thanks for the quick response @webbertakken ! Here it is:
```
name: Run Unit Tests

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - Test-Project
        unityVersion:
          - 2019.3.6f1
          - 2020.1.0b4
        testMode:
          - editmode
          - playmode
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-
      - uses: webbertakken/unity-test-runner@v1.6
        id: tests
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
```

My best guess is that the license activates fine but it fails to open the editor / the editor is crashing somehow.

**Comment by webbertakken** [comment] 2020-04-03 15:16
Hmm it doesn't really become clear from these logs what's going on.

You're right about that it looks like the license activates but then the editor crashes. Note that activating already happens within the editor itself. So it's when trying to run your tests that it crashes.

Possibly a permission issue. Otherwise perhaps a misconfiguration of assembly files. Either way we need to find a better way to get logs out of unity.

**Comment by DooblyNoobly** [comment] 2020-04-08 00:03
I'm getting the exact problem with our tests: https://github.com/unitystation/unitystation/actions

Here is our test config: https://github.com/unitystation/unitystation/blob/develop/.github/workflows/test.yml

We also just upgraded from Unity 2019.2 to 2019.3. It would work most of the time when we were on 2019.2 but every now and then would throw the urinary error:

`/steps/run_tests.sh: line 164: [: =: unary operator expected
/steps/run_tests.sh: line 182: [: -gt: unary operator expected`

Now after upgrading to 2019.3 it fails with that error all the time

**Comment by webbertakken** [comment] 2020-04-08 08:29
Good to know it doesn't always happen, and that there seems to be a difference between Unity versions. I'd say that rules out misconfiguration of test assembly files.

I doubt the `unary operator` being the reason for the actual failure, and still think the failure is silent. On the runs where it doesn't fail, does it also give you the errors about `unary operator`?

**Comment by DooblyNoobly** [comment] 2020-04-09 00:12
So this is what those logs look like in a test that passes:

```2020-04-06T21:45:55.5686104Z cat: write error: Resource temporarily unavailable
2020-04-06T21:45:55.5686712Z /steps/run_tests.sh: line 109: [: =: unary operator expected
2020-04-06T21:45:55.5687144Z /steps/run_tests.sh: line 164: [: =: unary operator expected
2020-04-06T21:45:55.5687908Z /steps/run_tests.sh: line 182: [: -gt: unary operator expected
2020-04-06T21:45:55.7803486Z ##[group]Run actions/setup-dotnet@v1```

**Comment by webbertakken** [comment] 2020-04-09 10:11
Yea so it is really about Unity not giving us enough information about what's going on. 

I think we need to get more information out of either unity or the test script specifically.

**Comment by webbertakken** [comment] 2020-06-02 21:56
Duplicate of https://github.com/webbertakken/unity-actions/issues/70#issuecomment-637817909

This issue can be resolved by using stable, non-beta versions.

**Closed by webbertakken** 2020-06-02 21:56 UTC
Labels: bug in unity, wontfix

**Comment by webbertakken** [comment] 2021-04-23 22:14
See also https://github.com/game-ci/unity-actions/issues/84
